version: '3.8'

services:
  ibicos-frontend:
    stdin_open: true
    tty: true
    network_mode: host
    container_name: ibicos-frontend-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ibicos-frontend-data:/ibicos-frontend/node_modules
    image: ibicos-frontend:dev

volumes:
  ibicos-frontend-data:
